spring:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/carparkingservice-db?createDatabaseIfNotExist=true
    username: root
    password:

#  security:
#    user:
#      name: user
#      password: password
